# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JmpvuBI8cdFgVqhInvO9-dxGylQtxlh-
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import category_encoders as ce

import numpy as np

from log_regression import LogRegression
from ann import ANN
from ann import binary_crossentropy, Sigmoid, Tanh

url = 'https://raw.githubusercontent.com/karencfisher/DS-Unit-3-Sprint-2-SQL-and-Databases/master/module2-sql-for-analysis/titanic.csv'
df = pd.read_csv(url)

df.drop('Name', axis=1, inplace=True)

X_train, X_test, y_train, y_test = train_test_split(df.drop('Survived', axis=1),
                                                    df['Survived'], test_size=.2,
                                                    random_state=42)

oe = ce.OrdinalEncoder()
scaler = StandardScaler()

X_train = oe.fit_transform(X_train)
X_train = scaler.fit_transform(X_train)
X_train = X_train.T
X_test = oe.transform(X_test)
X_test = scaler.transform(X_test)
X_test = X_test.T

y_train = np.array(y_train).reshape(1, -1)
y_test = np.array(y_test).reshape(1, -1)

clf = ANN(X_train.shape, 0.05, binary_crossentropy)
clf.add_layer(5, Tanh)
clf.add_layer(1, Sigmoid)

clf.fit(X_train, y_train, 1000, verbose=100)

import matplotlib.pyplot as plt
plt.plot(clf.losses, label='train loss')
plt.plot(clf.accuracies, label='train accuracy')
plt.legend();


